### PR TITLE
Ignore loading helper in API-based controller

### PR DESCRIPTION
**Pull request by mitsuru**
If a controller based on ActionController::API exists, it no longer works with devise-i18n 1.11.1.
The API does not use view helper, so I have changed it to not load it if the `helper` method is not present

```
NoMethodError:
  undefined method `helper' for ActionController::API:Class
# /usr/local/bundle/gems/devise-i18n-1.11.1/lib/devise-i18n/railtie.rb:9:in `block (2 levels) in <class:Engine>'
# /usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
# /usr/local/bundle/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
# /usr/local/bundle/gems/doorkeeper-5.6.6/lib/doorkeeper/config.rb:477:in `resolve_controller'
# /usr/local/bundle/gems/doorkeeper-5.6.6/app/controllers/doorkeeper/application_metal_controller.rb:5:in `<module:Doorkeeper>'
# /usr/local/bundle/gems/doorkeeper-5.6.6/app/controllers/doorkeeper/application_metal_controller.rb:3:in `<top (required)>'
... snip ...
```

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Thanks!

**Comment by JasonBarnabe** [comment]
Included in 1.12.0.
